apiVersion: v1
kind: Template
metadata:
  name: test-amq-base-build
  annotations:
    openshift.io/display-name: Test S2I JBoss AMQ Broker
    description: Template to build a Test JBoss AMQ Broker using S2I
    iconClass: icon-jboss
    tags: messaging,amq,jboss,xpaas
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${NAME}
    name: ${NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${NAME}
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:${OUTPUT_TAG}
    source:
      contextDir: ${CONTEXT_DIR}
      git:
        uri: ${GIT_REPO}
        ref: ${GIT_REF}
      sourceSecret:
        name: ${GIT_SOURCE_SECRET}
        type: Git
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: ${BASE_IMAGESTREAM_NAME}:${BASE_IMAGESTREAM_TAG}
          namespace: ${BASE_IMAGESTREAM_NAMESPACE}
      type: Docker
parameters:
- name: NAME
  displayName: Name
  description: Name of the Application
  value: test-jboss-amq
  required: true
- name: GIT_REPO
  displayName: Git Source Repo
  value: https://github.com/hawkdshrh/fuse-example/tree/master/activemq/test-amq-s2i
- name: GIT_REF
  displayName: Git Source Ref
  value: prometheus
- name: GIT_SOURCE_SECRET
  displayName: Git Source Secret Name
  value: test-amq-github
- name: CONTEXT_DIR
  displayName: Git Context Directory
  value: /test-amq-s2i
- name: BASE_IMAGESTREAM_NAME
  displayName: Base ImageStream
  description: Name of the Base ImageStream
  value: jboss-amq-63
  required: true
- name: BASE_IMAGESTREAM_TAG
  displayName: Base ImageStream Tag
  description: Base ImageStream Tag
  value: "1.2"
  required: true
- name: BASE_IMAGESTREAM_NAMESPACE
  displayName: Base ImageStream Namespace
  description: Base ImageStream Namespace
  value: "openshift"
- name: OUTPUT_TAG
  displayName: Output Tag
  description: Tag for the Resulting Output Image
  value: "latest"
