apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: registry-cluster
  namespace: registry
spec:
  entityOperator:
    topicOperator: {}
    userOperator: {}
  kafka:
    authorization:
      type: simple
    config:
      default.replication.factor: 1
      inter.broker.protocol.version: '3.4'
      min.insync.replicas: 1
      offsets.topic.replication.factor: 1
      transaction.state.log.min.isr: 1
      transaction.state.log.replication.factor: 1
    listeners:
      - authentication:
          type: tls
        name: tls
        port: 9092
        tls: true
        type: internal
    replicas: 1
    storage:
      type: ephemeral
    version: 3.4.0
  zookeeper:
    replicas: 1
    storage:
      type: ephemeral

